name: taxonomies
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  from_zero_ui:
    path: ../from_zero_ui/

  # * Language Extensions
  dartx: 0.7.0
  dio: 3.0.10
  dio_retry: 0.1.9-beta
  poly: ^1.0.7+2

  # * State Management
  provider: 5.0.0
  hive: 2.0.0
  hive_flutter: 1.0.0

  # * Widgets / UI
  flutter_icons: 1.1.0
  animations: 2.0.0
  auto_size_text: 2.1.0
  extended_tabs: any
  flutter_typeahead: 3.1.3
  flutter_svg: ^0.22.0
#  flutter_map: ^0.10.1+1
#  user_location:
#    git:
#      url: https://github.com/igaurab/user_location_plugin.git
#  flutter_map_tappable_polyline: ^1.1.1

  # * Plugins
#  archive: ^2.0.13
  url_launcher: 6.0.2
  path_provider: 2.0.1
  moor: 4.1.0
  moor_ffi: 0.8.0
  shared_preferences: 2.0.6
  sqlite3_flutter_libs: 0.4.0+1
#  audioplayer: ^0.8.1
#  audioplayer_web: ^0.7.1
  assets_audio_player: 2.0.13+1
  flutter_audio_desktop: 0.0.8
  video_player: 1.0.1
  video_player_web: 0.1.4+1
  chewie: 0.12.0
  downloads_path_provider: 0.1.0
  permission_handler: 6.1.0
  qr_code_scanner: 0.3.0
  open_file: 3.2.1
  location: 4.1.1
  uni_links: 0.5.1
  image: 3.0.2
  clipboard: 0.1.3
  share_plus: 2.1.2

  utf: 0.9.0+5

  # ! temporal fde dependencies until official desktop support is stable
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 040f36c82b63e8764ec2fd97066767503a667b6d

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: 0.13.0
  http_parser: 4.0.0
  crypto: 3.0.0
  path_provider: 2.0.1
  sqlite3_flutter_libs: 0.4.0+1
  moor: 4.1.0
  ffi: 1.0.0
  convert: 3.0.0
  xml: ^5.0.0
  path_parsing: ^0.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/
    - assets/audios/
    - assets/pictures/
    - assets/videos/
#    - assets/ads/
#    - assets/audio/
#    - assets/image/
#    - assets/map/
#    - assets/video/
    - assets/games/
#    - assets/icon/
#    - assets/icon/abundance/
#    - assets/icon/activity/
#    - assets/icon/conserv/
#    - assets/icon/diet/
#    - assets/icon/habitat/
#    - assets/icon/new/
